use crate::{
    coverage::lcov,
    error::Result,
    store::{BaselineStore, StructuredStore},
};
use chrono::Utc;
use std::path::Path;

pub struct ContextOptions {
    pub worktree: Option<String>,
    pub output: String,
    pub min_coverage: f64,
}

impl Default for ContextOptions {
    fn default() -> Self {
        Self {
            worktree: None,
            output: "AGENTS.md".into(),
            min_coverage: 85.0,
        }
    }
}

pub fn generate(
    root: &Path,
    store: &StructuredStore,
    baselines: &BaselineStore,
    opts: &ContextOptions,
) -> Result<String> {
    let mut out = String::new();
    let ts = Utc::now().format("%Y-%m-%dT%H:%MZ");

    push_header(&mut out, &opts.worktree, &ts.to_string());
    push_worktrees(&mut out, store, &opts.worktree)?;
    push_decisions(&mut out, store)?;
    push_coverage_summary(&mut out, root, baselines, opts.min_coverage);
    push_usage(&mut out);

    Ok(out)
}

fn push_header(out: &mut String, worktree: &Option<String>, ts: &str) {
    let scope = worktree.as_deref().unwrap_or("project-wide");
    out.push_str(&format!("# Agent Context — {scope} [generated {ts}]\n\n"));
    out.push_str("> Auto-generated by spec-store. Do not edit manually.\n\n");
}

fn push_worktrees(
    out: &mut String,
    store: &StructuredStore,
    active: &Option<String>,
) -> Result<()> {
    let worktrees = store.list_worktrees()?;
    if worktrees.is_empty() {
        return Ok(());
    }

    out.push_str("## Active Worktrees\n\n");
    if let Some(branch) = active {
        if let Some(wt) = worktrees.iter().find(|w| &w.branch == branch) {
            out.push_str(&format!("**Your scope:** `{}`", wt.branch));
            if let Some(c) = &wt.contract {
                out.push_str(&format!(" — contract: `{c}`"));
            }
            out.push('\n');
        }
    }

    out.push_str("\n**Do not modify files owned by these worktrees:**\n\n");
    for wt in &worktrees {
        if active.as_deref() == Some(&wt.branch) {
            continue;
        }
        let owner = wt.owner.as_deref().unwrap_or("unassigned");
        out.push_str(&format!("- `{}` ({})", wt.branch, owner));
        if let Some(c) = &wt.contract {
            out.push_str(&format!(" → `{c}`"));
        }
        out.push('\n');
    }
    out.push('\n');
    Ok(())
}

fn push_decisions(out: &mut String, store: &StructuredStore) -> Result<()> {
    let decisions = store.list_decisions()?;
    if decisions.is_empty() {
        return Ok(());
    }

    out.push_str("## Architectural Decisions\n\n");
    out.push_str("These decisions apply to all code in this project:\n\n");
    for d in decisions.iter().take(10) {
        let date = &d.created_at[..10];
        out.push_str(&format!("- [{date}] {}\n", d.text));
    }
    if decisions.len() > 10 {
        out.push_str(&format!(
            "\n*{} more — run `spec-store decision list` to see all.*\n",
            decisions.len() - 10
        ));
    }
    out.push('\n');
    Ok(())
}

fn push_coverage_summary(
    out: &mut String,
    root: &Path,
    baselines: &BaselineStore,
    min_coverage: f64,
) {
    let lcov_path = root.join("lcov.info");
    let total: usize = baselines.all_entries().count();
    if total == 0 {
        return;
    }

    out.push_str("## Coverage\n\n");
    out.push_str(&format!(
        "**Threshold:** {min_coverage:.1}% per file | **Tracked files:** {total}\n\n"
    ));

    if lcov_path.exists() {
        if let Ok(coverage) = lcov::parse(&lcov_path) {
            let passing = coverage
                .values()
                .filter(|f| f.percentage() >= min_coverage)
                .count();
            out.push_str(&format!(
                "**Current:** {passing}/{} files passing\n\n",
                coverage.len()
            ));
        }
    } else {
        out.push_str("Run your test suite and `cargo llvm-cov --lcov` to update.\n\n");
    }
}

fn push_usage(out: &mut String) {
    out.push_str("## How to Query the Store\n\n");
    out.push_str("```bash\n");
    out.push_str("spec-store search \"<what you're looking for>\"\n");
    out.push_str("spec-store decision list\n");
    out.push_str("spec-store worktree list\n");
    out.push_str("spec-store coverage report\n");
    out.push_str("spec-store quality check --path src/\n");
    out.push_str("```\n\n");
    out.push_str("**Before writing new functions:** `spec-store search \"<intent>\"`  \n");
    out.push_str("**Before pushing:** `spec-store coverage check`\n");
}

pub fn write(root: &Path, content: &str, output: &str) -> Result<()> {
    let path = if output.starts_with('/') {
        std::path::PathBuf::from(output)
    } else {
        root.join(output)
    };
    std::fs::write(&path, content).map_err(crate::error::SpecStoreError::Io)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::{BaselineStore, StructuredStore};

    fn make_store() -> StructuredStore {
        StructuredStore::open_in_memory().unwrap()
    }

    #[test]
    fn generate_produces_non_empty_output() {
        let store = make_store();
        let bl = BaselineStore::new_empty();
        let opts = ContextOptions::default();
        let out = generate(Path::new("."), &store, &bl, &opts).unwrap();
        assert!(!out.is_empty());
    }

    #[test]
    fn header_includes_timestamp() {
        let store = make_store();
        let bl = BaselineStore::new_empty();
        let opts = ContextOptions::default();
        let out = generate(Path::new("."), &store, &bl, &opts).unwrap();
        assert!(out.contains("generated"));
    }

    #[test]
    fn decisions_appear_in_output() {
        let store = make_store();
        store
            .add_decision("Use HMAC tokens everywhere", &[])
            .unwrap();
        let bl = BaselineStore::new_empty();
        let opts = ContextOptions::default();
        let out = generate(Path::new("."), &store, &bl, &opts).unwrap();
        assert!(out.contains("HMAC"));
    }

    #[test]
    fn worktrees_appear_in_output() {
        let store = make_store();
        store
            .claim_worktree("feat/auth", None, Some("agent-1"))
            .unwrap();
        let bl = BaselineStore::new_empty();
        let opts = ContextOptions {
            worktree: Some("feat/spend".into()),
            output: "AGENTS.md".into(),
            min_coverage: 85.0,
        };
        let out = generate(Path::new("."), &store, &bl, &opts).unwrap();
        assert!(out.contains("feat/auth"));
    }

    #[test]
    fn usage_section_always_present() {
        let store = make_store();
        let bl = BaselineStore::new_empty();
        let opts = ContextOptions::default();
        let out = generate(Path::new("."), &store, &bl, &opts).unwrap();
        assert!(out.contains("spec-store search"));
    }
}
