//! Parameter structs for MCP tools. Each derives JsonSchema for auto-generated schemas.

use rmcp::schemars;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct SearchParams {
    /// Natural language query
    pub query: String,
    /// Max results to return (default 5)
    pub limit: Option<usize>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct RegisterFnParams {
    /// Function name
    pub name: String,
    /// Source file path
    pub file: String,
    /// Line number (default 0)
    pub line: Option<usize>,
    /// Description of what the function does (provided by the calling agent, not generated by spec-store)
    pub description: String,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct AddDecisionParams {
    /// Decision text
    pub text: String,
    /// Optional tags
    pub tags: Option<Vec<String>>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct CoverageParams {
    /// Path to lcov file (defaults to config value)
    pub from: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct QualityParams {
    /// Directory path to check
    pub path: Option<String>,
    /// Single file to check
    pub file: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct PathParams {
    /// Directory to scan (defaults to src/)
    pub path: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct ClaimWorktreeParams {
    /// Branch name to claim
    pub branch: String,
    /// Optional contract file path
    pub contract: Option<String>,
    /// Optional owner identifier
    pub owner: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct BranchParams {
    /// Branch name
    pub branch: String,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct FnCoverageParams {
    /// Path to lcov file (defaults to config value)
    pub from: Option<String>,
    /// Filter results to functions matching this name
    pub function_name: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct TestMappingsParams {
    /// Directory to scan (defaults to src/)
    pub path: Option<String>,
    /// Filter mappings to this function name
    pub function_name: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct ReuseCheckParams {
    /// Function name
    pub name: String,
    /// Source file path
    pub file: String,
    /// Description of intended functionality
    pub description: String,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct InitParams {
    /// Root directory (defaults to current directory)
    pub root: Option<String>,
}

#[derive(Serialize, JsonSchema)]
pub struct JsonResult {
    pub data: serde_json::Value,
}
