use rmcp::{
    handler::server::{
        tool::ToolRouter,
        wrapper::{Json, Parameters},
    },
    model::*,
    schemars,
    service::{RequestContext, RoleServer},
    tool, tool_handler, tool_router, ErrorData, ServerHandler,
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use spec_store_core::{ops, AppContext};
use std::sync::Mutex;

pub struct SpecStoreServer {
    ctx: Mutex<Option<AppContext>>,
    tool_router: ToolRouter<Self>,
}

impl SpecStoreServer {
    pub fn new() -> Self {
        let ctx = match AppContext::load() {
            Ok(ctx) => {
                tracing::info!("spec-store context loaded from {:?}", ctx.root);
                Some(ctx)
            }
            Err(e) => {
                tracing::warn!("spec-store context not available: {e}");
                None
            }
        };
        Self {
            ctx: Mutex::new(ctx),
            tool_router: Self::tool_router(),
        }
    }

    /// Borrow the context, returning an error JSON result if not loaded.
    fn with_ctx<F>(&self, f: F) -> Json<JsonResult>
    where
        F: FnOnce(&AppContext) -> Json<JsonResult>,
    {
        let guard = self.ctx.lock().unwrap();
        match guard.as_ref() {
            Some(ctx) => f(ctx),
            None => Json(JsonResult {
                data: serde_json::json!({"error": "No spec-store project found. Run `spec-store init` in your project first."}),
            }),
        }
    }

    /// Borrow the context mutably.
    fn with_ctx_mut<F>(&self, f: F) -> Json<JsonResult>
    where
        F: FnOnce(&mut AppContext) -> Json<JsonResult>,
    {
        let mut guard = self.ctx.lock().unwrap();
        match guard.as_mut() {
            Some(ctx) => f(ctx),
            None => Json(JsonResult {
                data: serde_json::json!({"error": "No spec-store project found. Run `spec-store init` in your project first."}),
            }),
        }
    }
}

// ── Parameter structs ─────────────────────────────────────────────────

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct SearchParams {
    /// Natural language query
    pub query: String,
    /// Max results to return (default 5)
    pub limit: Option<usize>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct RegisterFnParams {
    /// Function name
    pub name: String,
    /// Source file path
    pub file: String,
    /// Line number (default 0)
    pub line: Option<usize>,
    /// Description of what the function does (provided by the calling agent, not generated by spec-store)
    pub description: String,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct AddDecisionParams {
    /// Decision text
    pub text: String,
    /// Optional tags
    pub tags: Option<Vec<String>>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct CoverageParams {
    /// Path to lcov file (defaults to config value)
    pub from: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct QualityParams {
    /// Directory path to check
    pub path: Option<String>,
    /// Single file to check
    pub file: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct PathParams {
    /// Directory to scan (defaults to src/)
    pub path: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct ClaimWorktreeParams {
    /// Branch name to claim
    pub branch: String,
    /// Optional contract file path
    pub contract: Option<String>,
    /// Optional owner identifier
    pub owner: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct BranchParams {
    /// Branch name
    pub branch: String,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct FnCoverageParams {
    /// Path to lcov file (defaults to config value)
    pub from: Option<String>,
    /// Filter results to functions matching this name
    pub function_name: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct TestMappingsParams {
    /// Directory to scan (defaults to src/)
    pub path: Option<String>,
    /// Filter mappings to this function name
    pub function_name: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct ReuseCheckParams {
    /// Function name
    pub name: String,
    /// Source file path
    pub file: String,
    /// Description of intended functionality
    pub description: String,
}

#[derive(Debug, Deserialize, JsonSchema, Default)]
pub struct InitParams {
    /// Root directory (defaults to current directory)
    pub root: Option<String>,
}

// ── Serialisable response ─────────────────────────────────────────────

#[derive(Serialize, JsonSchema)]
pub struct JsonResult {
    pub data: serde_json::Value,
}

// ── Tool implementations ──────────────────────────────────────────────

#[tool_router]
impl SpecStoreServer {
    #[tool(
        name = "search",
        description = "Semantic search across registered functions and decisions"
    )]
    fn search(&self, Parameters(p): Parameters<SearchParams>) -> Json<JsonResult> {
        self.with_ctx(|ctx| {
            let results = ops::search(ctx, &p.query, p.limit.unwrap_or(5));
            let out: Vec<serde_json::Value> = results
                .iter()
                .map(|r| {
                    serde_json::json!({
                        "id": r.id, "score": r.score,
                        "name": r.payload["name"], "file": r.payload["file"],
                        "description": r.payload["description"],
                    })
                })
                .collect();
            Json(JsonResult {
                data: serde_json::json!(out),
            })
        })
    }

    #[tool(
        name = "register_fn",
        description = "Register a function in the store and vector index. The calling agent should provide the description — spec-store does not generate descriptions."
    )]
    fn register_fn(&self, Parameters(p): Parameters<RegisterFnParams>) -> Json<JsonResult> {
        self.with_ctx_mut(|ctx| {
            match ops::register_fn(ctx, &p.name, &p.file, p.line.unwrap_or(0), &p.description) {
                Ok(id) => Json(JsonResult {
                    data: serde_json::json!({"id": id, "status": "registered"}),
                }),
                Err(e) => Json(JsonResult {
                    data: serde_json::json!({"error": e.to_string()}),
                }),
            }
        })
    }

    #[tool(
        name = "add_decision",
        description = "Record an architectural decision"
    )]
    fn add_decision(&self, Parameters(p): Parameters<AddDecisionParams>) -> Json<JsonResult> {
        self.with_ctx_mut(|ctx| {
            let tags = p.tags.clone().unwrap_or_default();
            match ops::add_decision(ctx, &p.text, &tags) {
                Ok(id) => Json(JsonResult {
                    data: serde_json::json!({"id": id, "status": "recorded"}),
                }),
                Err(e) => Json(JsonResult {
                    data: serde_json::json!({"error": e.to_string()}),
                }),
            }
        })
    }

    #[tool(
        name = "list_decisions",
        description = "List all architectural decisions"
    )]
    fn list_decisions(&self) -> Json<JsonResult> {
        self.with_ctx(|ctx| match ops::list_decisions(ctx) {
            Ok(decisions) => {
                let out: Vec<serde_json::Value> = decisions
                    .iter()
                    .map(|d| {
                        serde_json::json!({"id": d.id, "text": d.text, "tags": d.tags, "created_at": d.created_at})
                    })
                    .collect();
                Json(JsonResult {
                    data: serde_json::json!(out),
                })
            }
            Err(e) => Json(JsonResult {
                data: serde_json::json!({"error": e.to_string()}),
            }),
        })
    }

    #[tool(
        name = "check_coverage",
        description = "Run coverage gates against lcov.info and return results"
    )]
    fn check_coverage(&self, Parameters(p): Parameters<CoverageParams>) -> Json<JsonResult> {
        self.with_ctx(|ctx| match ops::check_coverage(ctx, p.from.as_deref()) {
            Ok(report) => {
                let out: Vec<serde_json::Value> = report
                    .results
                    .iter()
                    .map(|r| {
                        serde_json::json!({"file": r.file(), "pct": r.pct(), "status": if r.is_failure() { "failed" } else { "passed" }})
                    })
                    .collect();
                Json(JsonResult {
                    data: serde_json::json!(out),
                })
            }
            Err(e) => Json(JsonResult {
                data: serde_json::json!({"error": e.to_string()}),
            }),
        })
    }

    #[tool(
        name = "check_quality",
        description = "Run quality gates on a path and return violations"
    )]
    fn check_quality(&self, Parameters(p): Parameters<QualityParams>) -> Json<JsonResult> {
        self.with_ctx(|ctx| {
            match ops::check_quality(ctx, p.path.as_deref(), p.file.as_deref()) {
                Ok(violations) => {
                    let out: Vec<serde_json::Value> = violations
                        .iter()
                        .filter(|fv| !fv.violations.is_empty())
                        .map(|fv| {
                            serde_json::json!({
                                "file": fv.file,
                                "violations": fv.violations.iter().map(|v| {
                                    serde_json::json!({"message": v.message, "is_warning": v.is_warning})
                                }).collect::<Vec<_>>(),
                            })
                        })
                        .collect();
                    Json(JsonResult {
                        data: serde_json::json!(out),
                    })
                }
                Err(e) => Json(JsonResult {
                    data: serde_json::json!({"error": e.to_string()}),
                }),
            }
        })
    }

    #[tool(
        name = "scan_functions",
        description = "Scan a path for functions and return their metadata"
    )]
    fn scan_functions(&self, Parameters(p): Parameters<PathParams>) -> Json<JsonResult> {
        self.with_ctx(|ctx| {
            let path = p
                .path
                .as_deref()
                .map(std::path::PathBuf::from)
                .unwrap_or_else(|| ctx.root.join("src"));
            let fns = ops::scan_functions(&path);
            let out: Vec<serde_json::Value> = fns
                .iter()
                .map(|f| {
                    serde_json::json!({"name": f.name, "file": f.file, "line": f.line, "line_count": f.line_count, "param_count": f.param_count, "complexity": f.complexity, "is_test": f.is_test})
                })
                .collect();
            Json(JsonResult {
                data: serde_json::json!(out),
            })
        })
    }

    #[tool(
        name = "catchup",
        description = "Find unregistered functions in the codebase"
    )]
    fn catchup(&self, Parameters(p): Parameters<PathParams>) -> Json<JsonResult> {
        self.with_ctx(|ctx| match ops::catchup(ctx, p.path.as_deref(), false) {
            Ok(result) => {
                let missing: Vec<serde_json::Value> = result
                    .missing
                    .iter()
                    .map(|f| serde_json::json!({"name": f.name, "file": f.file, "line": f.line}))
                    .collect();
                Json(JsonResult {
                    data: serde_json::json!({"missing": missing, "total_scanned": result.total_scanned}),
                })
            }
            Err(e) => Json(JsonResult {
                data: serde_json::json!({"error": e.to_string()}),
            }),
        })
    }

    #[tool(
        name = "claim_worktree",
        description = "Claim a worktree branch for exclusive development"
    )]
    fn claim_worktree(&self, Parameters(p): Parameters<ClaimWorktreeParams>) -> Json<JsonResult> {
        self.with_ctx_mut(|ctx| {
            match ops::claim_worktree(ctx, &p.branch, p.contract.as_deref(), p.owner.as_deref()) {
                Ok(()) => Json(JsonResult {
                    data: serde_json::json!({"status": "claimed", "branch": p.branch}),
                }),
                Err(e) => Json(JsonResult {
                    data: serde_json::json!({"error": e.to_string()}),
                }),
            }
        })
    }

    #[tool(name = "release_worktree", description = "Release a worktree claim")]
    fn release_worktree(&self, Parameters(p): Parameters<BranchParams>) -> Json<JsonResult> {
        self.with_ctx_mut(|ctx| match ops::release_worktree(ctx, &p.branch) {
            Ok(()) => Json(JsonResult {
                data: serde_json::json!({"status": "released", "branch": p.branch}),
            }),
            Err(e) => Json(JsonResult {
                data: serde_json::json!({"error": e.to_string()}),
            }),
        })
    }

    #[tool(name = "list_worktrees", description = "List active worktree claims")]
    fn list_worktrees(&self) -> Json<JsonResult> {
        self.with_ctx(|ctx| match ops::list_worktrees(ctx) {
            Ok(wts) => {
                let out: Vec<serde_json::Value> = wts
                    .iter()
                    .map(|wt| {
                        serde_json::json!({"branch": wt.branch, "contract": wt.contract, "owner": wt.owner, "claimed_at": wt.claimed_at})
                    })
                    .collect();
                Json(JsonResult {
                    data: serde_json::json!(out),
                })
            }
            Err(e) => Json(JsonResult {
                data: serde_json::json!({"error": e.to_string()}),
            }),
        })
    }

    #[tool(
        name = "reuse_check",
        description = "Check a function against the similarity/reuse gate"
    )]
    fn reuse_check(&self, Parameters(p): Parameters<ReuseCheckParams>) -> Json<JsonResult> {
        self.with_ctx(|ctx| {
            let func = spec_store_core::scanner::FunctionInfo {
                name: p.name.clone(),
                file: p.file.clone(),
                line: 0,
                line_count: 0,
                param_count: 0,
                complexity: 1,
                is_test: false,
            };
            let level = ops::reuse_check(ctx, &func, &p.description);
            let out = match &level {
                spec_store_core::reuse::SimilarityLevel::Clear => {
                    serde_json::json!({"level": "clear"})
                }
                spec_store_core::reuse::SimilarityLevel::Warning {
                    score,
                    similar_fn,
                    similar_file,
                } => {
                    serde_json::json!({"level": "warning", "score": score, "similar_fn": similar_fn, "similar_file": similar_file})
                }
                spec_store_core::reuse::SimilarityLevel::Blocked {
                    score,
                    similar_fn,
                    similar_file,
                } => {
                    serde_json::json!({"level": "blocked", "score": score, "similar_fn": similar_fn, "similar_file": similar_file})
                }
            };
            Json(JsonResult { data: out })
        })
    }

    #[tool(name = "init", description = "Initialise spec-store in a repository")]
    fn init(&self, Parameters(p): Parameters<InitParams>) -> Json<JsonResult> {
        let root = p
            .root
            .map(std::path::PathBuf::from)
            .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| ".".into()));
        match ops::init(&root) {
            Ok(()) => {
                // Reload context after init
                match AppContext::load() {
                    Ok(new_ctx) => {
                        let mut guard = self.ctx.lock().unwrap();
                        *guard = Some(new_ctx);
                    }
                    Err(e) => tracing::warn!("Failed to reload context after init: {e}"),
                }
                Json(JsonResult {
                    data: serde_json::json!({"status": "initialised", "root": root.display().to_string()}),
                })
            }
            Err(e) => Json(JsonResult {
                data: serde_json::json!({"error": e.to_string()}),
            }),
        }
    }

    #[tool(
        name = "status",
        description = "Project health summary: function count, decisions, worktrees, coverage baselines"
    )]
    fn status(&self) -> Json<JsonResult> {
        self.with_ctx(|ctx| match ops::status(ctx) {
            Ok(report) => Json(JsonResult {
                data: serde_json::json!({
                    "function_count": report.function_count,
                    "decision_count": report.decision_count,
                    "worktree_count": report.worktree_count,
                    "baseline_count": report.baseline_count,
                    "hooks_installed": report.hooks_installed,
                }),
            }),
            Err(e) => Json(JsonResult {
                data: serde_json::json!({"error": e.to_string()}),
            }),
        })
    }

    #[tool(
        name = "project_rules",
        description = "Get project rules, quality gates, architectural decisions, and development workflow. Read this before making changes to understand constraints and conventions."
    )]
    fn project_rules(&self) -> Json<JsonResult> {
        self.with_ctx(|ctx| match ops::project_rules(ctx) {
            Ok(rules) => Json(JsonResult {
                data: serde_json::json!({"rules": rules}),
            }),
            Err(e) => Json(JsonResult {
                data: serde_json::json!({"error": e.to_string()}),
            }),
        })
    }

    #[tool(
        name = "list_tests",
        description = "List all test functions found in the codebase"
    )]
    fn list_tests(&self, Parameters(p): Parameters<PathParams>) -> Json<JsonResult> {
        self.with_ctx(|ctx| {
            let path = p
                .path
                .as_deref()
                .map(std::path::PathBuf::from)
                .unwrap_or_else(|| ctx.root.join("src"));
            let tests = ops::test_tracking::list_tests(&path);
            let out: Vec<serde_json::Value> = tests
                .iter()
                .map(|f| {
                    serde_json::json!({"name": f.name, "file": f.file, "line": f.line, "line_count": f.line_count})
                })
                .collect();
            Json(JsonResult {
                data: serde_json::json!(out),
            })
        })
    }

    #[tool(
        name = "function_coverage",
        description = "Per-function coverage from LCOV data. Shows which functions are well-tested and which need more coverage."
    )]
    fn function_coverage(&self, Parameters(p): Parameters<FnCoverageParams>) -> Json<JsonResult> {
        self.with_ctx(|ctx| {
            match ops::test_tracking::function_coverage(
                ctx,
                p.from.as_deref(),
                p.function_name.as_deref(),
            ) {
                Ok(results) => {
                    let out: Vec<serde_json::Value> = results
                        .iter()
                        .map(|r| {
                            serde_json::json!({
                                "name": r.name, "file": r.file,
                                "is_test": r.is_test,
                                "pct": format!("{:.1}", r.percentage()),
                                "lines_found": r.lines_found,
                                "lines_hit": r.lines_hit,
                            })
                        })
                        .collect();
                    Json(JsonResult {
                        data: serde_json::json!(out),
                    })
                }
                Err(e) => Json(JsonResult {
                    data: serde_json::json!({"error": e.to_string()}),
                }),
            }
        })
    }

    #[tool(
        name = "test_mappings",
        description = "Show which tests cover which functions, using name and file heuristics"
    )]
    fn test_mappings(&self, Parameters(p): Parameters<TestMappingsParams>) -> Json<JsonResult> {
        self.with_ctx(|ctx| {
            let mappings = ops::test_tracking::test_mappings(
                ctx,
                p.path.as_deref(),
                p.function_name.as_deref(),
            );
            let out: Vec<serde_json::Value> = mappings
                .iter()
                .map(|m| {
                    serde_json::json!({
                        "function": {"name": m.function_name, "file": m.function_file},
                        "test": {"name": m.test_name, "file": m.test_file},
                        "match_type": m.match_type,
                    })
                })
                .collect();
            Json(JsonResult {
                data: serde_json::json!(out),
            })
        })
    }
}

#[tool_handler]
impl ServerHandler for SpecStoreServer {
    fn get_info(&self) -> ServerInfo {
        let mut caps = ServerCapabilities::default();
        caps.tools = Some(ToolsCapability::default());
        caps.resources = Some(ResourcesCapability::default());
        ServerInfo::new(caps).with_instructions(
            "spec-store manages a codebase specification registry with semantic search, \
             quality gates, coverage enforcement, and multi-agent worktree coordination. \
             IMPORTANT: Read the 'spec-store://rules' resource or call 'project_rules' tool \
             before making any code changes. Use 'search' before writing new functions. \
             Use 'check_quality' and 'check_coverage' before pushing.",
        )
    }

    fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ListResourcesResult, ErrorData>> + Send + '_ {
        let resources = vec![
            Annotated::new(
                RawResource {
                    uri: "spec-store://rules".into(),
                    name: "Project Rules".into(),
                    title: Some(
                        "spec-store project rules, quality gates, and conventions".into(),
                    ),
                    description: Some("Hard rules, architectural decisions, active worktrees, and development workflow. Read this before making code changes.".into()),
                    mime_type: Some("text/markdown".into()),
                    size: None,
                    icons: None,
                    meta: None,
                },
                None,
            ),
            Annotated::new(
                RawResource {
                    uri: "spec-store://config".into(),
                    name: "Configuration".into(),
                    title: Some("Current spec-store configuration".into()),
                    description: Some(
                        "Quality thresholds, coverage settings, and reuse gates.".into(),
                    ),
                    mime_type: Some("text/plain".into()),
                    size: None,
                    icons: None,
                    meta: None,
                },
                None,
            ),
        ];
        std::future::ready(Ok(ListResourcesResult {
            meta: None,
            resources,
            next_cursor: None,
        }))
    }

    fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ReadResourceResult, ErrorData>> + Send + '_ {
        let result = match request.uri.as_str() {
            "spec-store://rules" => {
                let guard = self.ctx.lock().unwrap();
                match guard.as_ref() {
                    Some(ctx) => match ops::project_rules(ctx) {
                        Ok(rules) => Ok(ReadResourceResult::new(vec![ResourceContents::text(
                            rules,
                            "spec-store://rules",
                        )])),
                        Err(e) => Err(ErrorData::internal_error(e.to_string(), None)),
                    },
                    None => Ok(ReadResourceResult::new(vec![ResourceContents::text(
                        "No spec-store project found. Run `spec-store init` first.",
                        "spec-store://rules",
                    )])),
                }
            }
            "spec-store://config" => {
                let guard = self.ctx.lock().unwrap();
                match guard.as_ref() {
                    Some(ctx) => {
                        let config_str = toml::to_string_pretty(&ctx.config)
                            .unwrap_or_else(|e| format!("Error serialising config: {e}"));
                        Ok(ReadResourceResult::new(vec![ResourceContents::text(
                            config_str,
                            "spec-store://config",
                        )]))
                    }
                    None => Ok(ReadResourceResult::new(vec![ResourceContents::text(
                        "No spec-store project found.",
                        "spec-store://config",
                    )])),
                }
            }
            _ => Err(ErrorData::resource_not_found(
                format!("Unknown resource: {}", request.uri),
                None,
            )),
        };
        std::future::ready(result)
    }
}
